### ISSUE TITLE
"Qt warning: Requested decoration  "adwaita"  not found, falling back to default" error with flatpak QT6 apps that use their own window decorations

### ISSUE THREAD

**Issue by n3thshan** [FedoraQt/QAdwaitaDecorations#73]
App: Anki
QT version of App: 6.6.2
PyQT version: 6.6.1

I installed the QAdwaitaDecorations all flatpak runtimes but still nothing works. I even set the environment variable QT_WAYLAND_DECORATION=adwaita. The app is also forced to run through wayland. Mind you, I am using gnome fractional scaling at 125%. Also, I did not install any other adwaita themes through flatpak except for adw-gtk3 theme. Regardless, I am getting this error and the window decorations are not applied. Please consider this. Thank you!

**Comment by n3thshan** [comment]
UPDATE: the behaviour is also present in the non-flatpak ANKI app as well. The issue, however, is not present when it is running on xwayland. on wayland it gives the same output as before. For more information, i am using Fedora 40 which has qadwaitadecorations installed by default. So why is it not able to apply it even with the environment variable exported? Is it because the app is using pyqt6?

**Comment by taoky** [comment]
Anki is using its own bundled PyQt6 implementation, and it does not bundle QAdwaitaDecorations. I think that you shall report the issue to <https://github.com/ankitects/anki/issues> instead of here. Its FlatHub version also just uses the GitHub release version of Anki: 

<https://github.com/flathub/net.ankiweb.Anki/blob/e46872ca79fb38d9150cef3c13de50d8caddac7d/net.ankiweb.Anki.yaml#L175-L183>

**Comment by n3thshan** [comment]
thx for the quick reply! later on i did notice that the official anki too has this problem. i will immediately draft an issue there.
